services:
  backend:
    image: simongigl/kochbuch.io-backend:latest
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: ${MONGODB_URI}
      SPRING_DATA_MONGODB_DATABASE: ${MONGODB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      HF_TOKEN: ${HF_TOKEN}
      ML_SERVICE_URL: http://ml-service:8000
      ML_SERVICE_API_KEY: ${ML_SERVICE_API_KEY}
    # depends_on: [ml-service]

  # ml-service:
  #   image: simongigl/kochbuch.io-ml-service:latest
  #   restart: unless-stopped
  #   environment:
  #     MONGODB_URI: ${MONGODB_URI}
  #     MONGODB_DATABASE: ${MONGODB_DATABASE}
  #     ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
  #     HF_TOKEN: ${HF_TOKEN}
  #     ML_SERVICE_API_KEY: ${ML_SERVICE_API_KEY}

  frontend:
    image: simongigl/kochbuch.io-frontend:latest
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on: [backend]

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"