services:
  backend:
    image: simongigl/kochbuch.io-backend:latest
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: ${MONGODB_URI}
      SPRING_DATA_MONGODB_DATABASE: ${MONGODB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    image: simongigl/kochbuch.io-frontend:latest
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on: [backend]