spring:
  servlet:
    multipart:
      max-file-size: "10MB"
  data:
    mongodb:
      uri: mongodb://localhost:27017/kochbuch_dev
      database: kochbuch_dev
jwt:
  secret: dev-only-not-a-real-secret