spring:
  servlet:
    multipart:
      max-file-size: "10MB"
  # data:
  #   mongodb:
      # uri: // in docker compose.yaml
      # database: // in docker compose.yaml
jwt:                                                                                                                                                                                                                                                        
  secret: ${JWT_SECRET}

app:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}

server:
  # ssl:
  #   key-store: classpath:keystore.jks
  #   key-store-password: Z*EhJDbgz6
  #   key-store-type: JKS
  #   key-alias: kochbuch.io
  #   enabled: true
  port: 8080